version: '3.9'

services:
    be_180112_db:
        image: mysql:8
        restart: always
        container_name: be_180112_db
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: prestashop
            MYSQL_ROOT_PASSWORD: prestashop
        ports:
            - 18013:3306
        volumes:
            - ./db:/docker-entrypoint-initdb.d
        networks:
            - prestashop
        
    be_180112_prestashop:
        container_name: be_180112_prestashop
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            DB_SERVER: be_180112_db
            PS_INSTALL_AUTO: 0
            PS_DOMAIN: localhost:18011
            PS_FOLDER_ADMIN: admindoll
            ALLOW_OVERRIDE: 1
        ports:
            - 18011:80 
            - 18012:443
        volumes:
          - ./prestashop:/var/www/html
          - ./prestashop/admindoll:/var/www/html/admindoll
          - ./prestashop/modules:/var/www/html/modules
          - ./prestashop/themes:/var/www/html/themes
          - ./prestashop/override:/var/www/html/override
        networks:
            - prestashop

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        environment:
            PMA_HOST: be_180112_db
        ports:
            - 1235:80
        networks:
            - prestashop
        depends_on:
            - be_180112_db

networks:
    prestashop:
