version: '3.9'

# a small comment to test git

services:
    mysql:
        image: mysql:8
        container_name: prestashop-db
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: prestashop
            MYSQL_ROOT_PASSWORD: prestashop
        ports:
            - 3306:3306
        volumes:
            - ./db:/var/lib/mysql
        networks:
            - prestashop
        
    prestashop:
        image: prestashop/prestashop:1.7
        container_name: prestashop
        environment:
            DB_SERVER: mysql
        ports:
            - 8080:80
        volumes:
          - ./prestashop:/var/www/html
        networks:
            - prestashop

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        environment:
            PMA_HOST: mysql
        ports:
            - 1235:80
        networks:
            - prestashop
        depends_on:
            - mysql

networks:
    prestashop:
