version: '3.9'

services:
    mysql:
        image: mysql:8
        restart: always
        container_name: prestashop-db
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: prestashop
            MYSQL_ROOT_PASSWORD: prestashop
        ports:
            - 3306:3306
        volumes:
            - ./db:/docker-entrypoint-initdb.d
        networks:
            - prestashop
        
    prestashop:
        container_name: prestashop
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            DB_SERVER: mysql
            PS_INSTALL_AUTO: 0
            PS_DOMAIN: localhost:80
            PS_FOLDER_ADMIN: admindoll
            ALLOW_OVERRIDE: 1
        ports:
            - 80:80 
            - 443:443
        volumes:
          - ./prestashop:/var/www/html
          - ./prestashop/admindoll:/var/www/html/admindoll
          - ./prestashop/modules:/var/www/html/modules
          - ./prestashop/themes:/var/www/html/themes
          - ./prestashop/override:/var/www/html/override
        networks:
            - prestashop

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        environment:
            PMA_HOST: mysql
        ports:
            - 1235:80
        networks:
            - prestashop
        depends_on:
            - mysql

networks:
    prestashop:
