#!/bin/bash

DATABASE_NAME="prestashop"
DATABASE_USER="be_180112"
DATABASE_PASSWORD="prestashop"
DATABASE_ROOT_PASSWORD="prestashop"
DATABASE_ROOT_LOGIN="root"
LOAD_FILE="./db/mysql.sql"

docker exec -it be_180112_db mysql -u$DATABASE_ROOT_LOGIN -p$DATABASE_ROOT_PASSWORD -e "CREATE DATABASE IF NOT EXISTS ${DATABASE_NAME};"
docker exec -it be_180112_db mysql -u$DATABASE_ROOT_LOGIN -p$DATABASE_ROOT_PASSWORD -e "CREATE USER IF NOT EXISTS ${DATABASE_USER}@'%' IDENTIFIED BY '${DATABASE_PASSWORD}';"
docker exec -it be_180112_db mysql -u$DATABASE_ROOT_LOGIN -p$DATABASE_ROOT_PASSWORD  -e "GRANT ALL PRIVILEGES ON ${DATABASE_NAME}.* TO '${DATABASE_USER}'@'%';"
docker exec -it be_180112_db mysql -u$DATABASE_ROOT_LOGIN -p$DATABASE_ROOT_PASSWORD  -e "FLUSH PRIVILEGES;"
docker exec -i be_180112_db mysql -u$DATABASE_ROOT_LOGIN -p$DATABASE_ROOT_PASSWORD $DATABASE_NAME < $LOAD_FILE

