<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7sufpvk\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7sufpvk/appProdProjectContainer.php') {
    touch(__DIR__.'/Container7sufpvk.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container7sufpvk\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container7sufpvk\appProdProjectContainer([
    'container.build_hash' => '7sufpvk',
    'container.build_id' => '5b732527',
    'container.build_time' => 1670611024,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7sufpvk');
