<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRx387ha\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRx387ha/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerRx387ha.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerRx387ha\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerRx387ha\appProdProjectContainer([
    'container.build_hash' => 'Rx387ha',
    'container.build_id' => '89a5cfd9',
    'container.build_time' => 1673958846,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRx387ha');
